[[redirects]]
    from = "/git/*"
    to = "https://ari.lt/lh/legacy.blog.ari.lt/:splat"
    status = 301
    force = true

[[redirects]]
    from = "/favicon.ico"
    to = "https://ari.lt/favicon.ico"
    status = 200
    force = true

[[redirects]]
    from = "/robots.txt"
    to = "https://ari.lt/robots.txt"
    status = 200
    force = true

[[redirects]]
    from = "/sitemap.xml"
    to = "https://ari.lt/sitemap.xml"
    status = 200
    force = true

[[redirects]]
    from = "/netlify.toml"
    to = "https://ari.lt/404.oldblog.xyz"
    status = 404
    force = true

[[redirects]]
    from = "/*"
    to = "https://ari.lt/404.oldblog.xyz"
    status = 404
    force = false

# Processing
[build.processing]
    skip_processing = false

[build.processing.html]
    pretty_urls = false

[build.processing.css]
    bundle = true
    minify = true

[build.processing.js]
    bundle = true
    minify = true

[build.processing.images]
    compress = true
# --------------

[[headers]]
    for = "/*"

    [headers.values]
        Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
        X-Frame-Options = "deny"
        X-Content-Type-Options = "nosniff"
        Content-Security-Policy = "upgrade-insecure-requests"
        X-Permitted-Cross-Domain-Policies = "none"
        Referrer-Policy = "no-referrer"

